[Custom_Field]
Path = "Administration > Devices > Device Custom Fields"
Type = "Checkbox"

[Overview]
Custom_field_type = "Checkbox"
Label = "cPVAL Enable Weak Credentials Monitoring"
Name = "cpvalEnableWeakCredentialsMonitoring"
Custom_field_is_required = false

[Inheritance]
Device = false
End_User = false
Location = false
Organization = true

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "Enable this checkbox to activate weak credential monitoring for the client's domain. The script will run against the client's primary domain controller."
Tooltip_text = "Turn on weak credential monitoring for this domain. The script will execute on the primary domain controller."
Footer_text = "This option runs a script on the client's primary domain controller to monitor weak credentials."

[Advanced_Settings]

[Advanced_Settings.WYSIWYG]
Expand_large_values_on_render = false

[Organization_Custom_Fields]
Path = "Administration > Organizations > Organization custom fields > Edit custom tabs > Manage tabs"
Custom_Field_Tab_Name = "Weak Credentials Monitoring"
Custom_Field_Tab_Description = "Stores custom fields related to the weak credentials monitoring"