[Custom_Field]
Path = "Administration > Organizations > Organization Custom Fields"
Type = "Text"

[Overview]
Custom_field_type = "Text"
Label = "cPVAL Excluded Domain Admin"
Name = "cpvalExcludedDomainAdmin"
Custom_field_is_required = false

[Inheritance]
Device = true
End_User = false
Location = true
Organization = true

[Permissions]
Automation = "Read_Write"
API = "Read_Write"
Technician_access = "Editable"

[Details]
Description = "Add the usernames to exclude from generating the new domain admin detected tickets. Multiple usernames can be added by separating them with a comma like AutomateTestAccount,FlyingBatman,FallingBatman"
Tooltip_text = "Add the usernames to exclude from generating the new domain admin detected tickets. Multiple usernames can be added by separating them with a comma like AutomateTestAccount,FlyingBatman,FallingBatman"
Footer_text = ""

[Device_Custom_Fields]

Path = "Administration > Devices > Roles"

[Device_Custom_Field.Role]
Role_Name = "Windows Server - Active Directory"
Custom_Field_Tab_Name = "New Domain Admin Monitoring Device"
Custom_Field_Description = "Custom Fields for new domain admin monitoring."

[Organization_Custom_Fields]
Path = "Administration > Organizations > Organization Custom Fields > Edit Custom Tabs > Manage tabs"
Custom_Field_Tab_Name = "New Domain Admin Monitoring"
Custom_Field_Description = "Custom Fields for new domain admin monitoring."

[Location_Custom_Fields]
Path = "Administration > Organizations > Location Custom Fields > Edit Custom Tabs > Manage tabs"
Custom_Field_Tab_Name = "New Domain Admin Monitoring"
Custom_Field_Description = "Custom Fields for new domain admin monitoring."