[ConnectWise_Manage_Ticket_Template]
Path = "Administration > Apps > Installed > ConnectWise Manage"

[Ticket_Template]
Name = "Weak AD Passwords"
Board = "Help Desk"
Status = "New"
Priority = "Priority 2 - High"
Type = "MUST CHANGE"
Sub_Type = ""
Item = ""
Source = "NinjaRMM"
Team = ""
Severity = "High"
Impact = "High"
Create_and_close_status = ""
Ticket_Title_Contents = "`Custom text` `Organization name`"
Custom_Text = "Weak AD Credentials Detected"
When_Condition_is_reset = "Do not change"
When_Condition_retriggers = "Create new ticket"

 # The details above may differ depending on environment. Please verify the required information with consultant or partner before completing these fields.