[Compound_Condition]
Path = "Administration > Policies > Agent Policies"
Agent_Policy = "Windows Server Policy [Default]"

[Conditions]
Trigger_when = "all conditions are true"

[Conditions.Custom_Fields]

[Conditions.Custom_Fields.Custom_field_value_must_meet_ALL_conditions]
Custom_field = "cPVAL Cisco Secure Client Modules"
Condition = "contains any"
Items = """
All
Core-VPN
Umbrella
Diagnostic And Reporting Tool
Network Visibility Module
ISE Posture
ThousandEyes Endpoint
Zero Trust Access
Start Before Login (Windows Only)
Network Access Manager (Windows Only)
VPN Posture (Windows Only)
"""

[Conditions.Custom_Fields.Custom_field_value_must_meet_ANY_conditions]
Custom_field = "cPVAL Cisco Secure Client Deployment"
Condition = "equals"
Dropdown_value = "All"

[Conditions.Custom_Fields.Custom_field_value_must_meet_ANY_conditions]
Custom_field = "cPVAL Cisco Secure Client Deployment"
Condition = "equals"
Dropdown_value = "Windows Server"

[Conditions.Custom_Fields.Custom_field_value_must_meet_ANY_conditions]
Custom_field = "cPVAL Cisco Secure Client Deployment"
Condition = "equals"
Dropdown_value = "Windows"

[Conditions.Script_result_condition]

[Conditions.Script_result_condition.Evaluation_script]
Evaluation_script = "Cisco Secure Client - Module Comparison [Windows]"

[Conditions.Script_result_condition.Evaluation_script.Parameters]
Run_As = "System"
Preset_Parameter = ""

[Conditions.Script_result_condition.Result_Code]
Operator = "equal to"
Result_Code = "1"

[Conditions.Script_result_condition.Timeout]
Hour = "0"
Minutes = "5"

[Conditions.Script_result_condition.Output]
Operator = "Contains"
Text = "The number of installed modules does not match the number of selected modules"

Include_Script_Output_in_final_Alert = true

[Conditions.Script_result_condition.Script_error_activity]
Script_error_activity = false
Operator = ""
Result_Code = ""

[Automations]

[Automations.Automation]
Name = "Cisco Secure Client - Package Installation [Windows]"

[Automations.Automation.Parameters]
Run_As = "System"
Preset_Parameter = ""

[Settings]
Name = "Cisco Secure Client - Package Installation [Windows Server]"

[Settings.Auto_Reset]
After = true
Reset_Interval = "4 hours"
When_no_longer_met = true

Run_Every = "1 hour"

[Settings.Trigger_uptime]
Trigger_uptime = false
Minimum_uptime_for_trigger = ""