[Compound_Condition]
Path = "Administration > Policies > Agent Policies"
Agent_Policy = "WIndows Server Policy [Default]"

[Conditions]
Trigger_when = "all conditions are true"

[Conditions.Custom_Fields]

[Conditions.Custom_Fields.Custom_field_value_must_meet_ALL_conditions]
Custom_field = "cPVAL Enable Weak Credentials Monitoring"
Condition = "equals"
Checkbox_value = true

[Conditions.Custom_Fields.Custom_field_value_must_meet_ALL_conditions]
Custom_field = "cPVAL Roles Detected"
Condition = "contains"
Text = "Infrastructure Master"

[Conditions.Script_result_condition]

[Conditions.Script_result_condition.Evaluation_script]
Evaluation_script = "Test Weak Password [Domain]"

[Conditions.Script_result_condition.Evaluation_script.Parameters]
Run_As = "System"
Preset_Parameter = ""
Password_Dictionary_Size = "Tiny"

[Conditions.Script_result_condition.Result_Code]
Operator = "equal to"
Result_Code = "1"

[Conditions.Script_result_condition.Timeout]
Hour = "0"
Minutes = "5"

[Conditions.Script_result_condition.Output]
Operator = "Contains"
Text = "password(s)"

Include_Script_Output_in_final_Alert = true

[Conditions.Script_result_condition.Script_error_notification]
Script_error_notification = false
Operator = ""
Result_Code = ""

[Automations]

[Settings]
Name = "Weak Credentials Monitoring"

[Settings.Auto_Reset]
After = false
Reset_Interval = ""
When_no_longer_met = true

Run_Every = "24 hours"

[Settings.Trigger_uptime]
Trigger_uptime = false
Minimum_uptime_for_trigger = ""

[Notifications]
Severity = "None"
Priority = "None"
Notify_Technicians = "Do not send notifications"
Notify_on_reset = false
Channels = ""
ConnectWise = "Create a ticket"

[Notifications.ConnectWise.Create_a_ticket]
Ticket_Template = "Weak AD Passwords"

Ticketing_Rule = "Off"